# Generated by Django 4.2.1 on 2023-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='titulo',
            new_name='libro',
        ),
    ]
